// lib/signal-goal-map.ts
// Single source of truth: signal_type → goal metadata → upsell service
// Used in: measure page (goal form), dashboard (goal cards + upsell)
// Never duplicate this mapping elsewhere

export const SIGNAL_GOAL_MAP: Record<string, {
  label:        string
  label_ar:     string
  metric:       string
  unit:         string
  lowerBetter:  boolean
  goalVerb:     string
  goalVerb_ar:  string
  service:      'roadmap' | 'cpo'
  serviceLabel: string
  servicePrice: string
  serviceUrl:   string
  upsellCopy:   string
  upsellCopy_ar: string
}> = {

  churn_spike: {
    label:         'Monthly Churn Rate',
    label_ar:      'معدل الاضطراب الشهري',
    metric:        'Churn %',
    unit:          '%',
    lowerBetter:   true,
    goalVerb:      'Reduce churn to',
    goalVerb_ar:   'خفِّض الاضطراب إلى',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'High churn needs a retention strategy — not just automation.',
    upsellCopy_ar: 'الاضطراب المرتفع يحتاج إلى استراتيجية احتفاظ — ليس مجرد أتمتة.',
  },
  ticket_volume_increase: {
    label:         'Support Ticket Volume',
    label_ar:      'حجم تذاكر الدعم',
    metric:        'Tickets / month',
    unit:          'tickets',
    lowerBetter:   true,
    goalVerb:      'Keep tickets under',
    goalVerb_ar:   'أبقِ التذاكر تحت',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/advisory?type=roadmap',
    upsellCopy:    'AI can automate triage, FAQs and saved replies to cut volume.',
    upsellCopy_ar: 'يمكن للذكاء الاصطناعي أتمتة التصنيف والأسئلة الشائعة لتقليل الحجم.',
  },
  response_time_increase: {
    label:         'Support Response Time',
    label_ar:      'وقت استجابة الدعم',
    metric:        'Avg hours to respond',
    unit:          'hours',
    lowerBetter:   true,
    goalVerb:      'Respond within',
    goalVerb_ar:   'استجب خلال',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/service-advisory?type=roadmap',
    upsellCopy:    'AI auto-response can cut response time by 60% without extra headcount.',
    upsellCopy_ar: 'الردود التلقائية بالذكاء الاصطناعي تقلل وقت الاستجابة 60% دون موظفين إضافيين.',
  },
  repeat_complaint_pattern: {
    label:         'Repeat Contact Rate',
    label_ar:      'معدل التواصل المتكرر',
    metric:        'Repeat contacts %',
    unit:          '%',
    lowerBetter:   true,
    goalVerb:      'Reduce repeat contacts to',
    goalVerb_ar:   'خفِّض التواصل المتكرر إلى',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/advisory?type=roadmap',
    upsellCopy:    'AI deflection and self-serve docs can eliminate repeat contacts.',
    upsellCopy_ar: 'توجيه الذكاء الاصطناعي والوثائق الذاتية يمكنها القضاء على التواصل المتكرر.',
  },
  nps_decline: {
    label:         'Net Promoter Score',
    label_ar:      'نقاط صافي المروجين',
    metric:        'NPS score',
    unit:          'points',
    lowerBetter:   false,
    goalVerb:      'Reach NPS of',
    goalVerb_ar:   'حقِّق NPS بقيمة',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'NPS improvement needs a product and retention strategy.',
    upsellCopy_ar: 'تحسين NPS يحتاج إلى استراتيجية منتج واحتفاظ.',
  },
  csat_decline: {
    label:         'Customer Satisfaction',
    label_ar:      'رضا العملاء',
    metric:        'CSAT %',
    unit:          '%',
    lowerBetter:   false,
    goalVerb:      'Reach CSAT of',
    goalVerb_ar:   'حقِّق CSAT بنسبة',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'CSAT recovery requires both product and operations strategy.',
    upsellCopy_ar: 'استعادة CSAT تتطلب استراتيجية منتج وعمليات معاً.',
  },
  velocity_drop: {
    label:         'Engineering Velocity',
    label_ar:      'سرعة الفريق التقني',
    metric:        'Story points / sprint',
    unit:          'points',
    lowerBetter:   false,
    goalVerb:      'Reach velocity of',
    goalVerb_ar:   'حقِّق سرعة تسليم بقيمة',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'Velocity recovery needs delivery prioritisation and process strategy.',
    upsellCopy_ar: 'استعادة السرعة تحتاج إلى تحديد أولويات التسليم واستراتيجية عمليات.',
  },
  bug_backlog_growth: {
    label:         'Bug Backlog',
    label_ar:      'تراكم الأخطاء',
    metric:        'Open critical bugs',
    unit:          'bugs',
    lowerBetter:   true,
    goalVerb:      'Keep critical bugs under',
    goalVerb_ar:   'أبقِ الأخطاء الحرجة تحت',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'A growing bug backlog signals a triage and process problem.',
    upsellCopy_ar: 'تراكم الأخطاء المتزايد يشير إلى مشكلة في التصنيف والعمليات.',
  },
  cycle_time_increase: {
    label:         'Engineering Cycle Time',
    label_ar:      'زمن دورة التطوير',
    metric:        'Days per ticket',
    unit:          'days',
    lowerBetter:   true,
    goalVerb:      'Reduce cycle time to',
    goalVerb_ar:   'خفِّض زمن الدورة إلى',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'Long cycle times need a workflow and dependency strategy.',
    upsellCopy_ar: 'أوقات الدورة الطويلة تحتاج إلى استراتيجية سير عمل وتبعيات.',
  },
  blocked_tickets_spike: {
    label:         'Blocked Tickets',
    label_ar:      'التذاكر المعلقة',
    metric:        'Blocked tickets count',
    unit:          'tickets',
    lowerBetter:   true,
    goalVerb:      'Reduce blocked tickets to',
    goalVerb_ar:   'خفِّض التذاكر المعلقة إلى',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'Blocked tickets signal team dependency and process issues.',
    upsellCopy_ar: 'التذاكر المعلقة تشير إلى مشاكل تبعيات الفريق والعمليات.',
  },
  conversion_fall: {
    label:         'Conversion Rate',
    label_ar:      'معدل التحويل',
    metric:        'Conversion %',
    unit:          '%',
    lowerBetter:   false,
    goalVerb:      'Reach conversion of',
    goalVerb_ar:   'حقِّق معدل تحويل بنسبة',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/advisory?type=roadmap',
    upsellCopy:    'AI personalisation and funnel automation can recover conversion.',
    upsellCopy_ar: 'التخصيص بالذكاء الاصطناعي وأتمتة القمع يمكنها استعادة معدل التحويل.',
  },
  engagement_drop: {
    label:         'User Engagement',
    label_ar:      'تفاعل المستخدمين',
    metric:        'Engagement rate %',
    unit:          '%',
    lowerBetter:   false,
    goalVerb:      'Reach engagement of',
    goalVerb_ar:   'حقِّق معدل تفاعل بنسبة',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/advisory?type=roadmap',
    upsellCopy:    'AI content recommendations can lift engagement significantly.',
    upsellCopy_ar: 'توصيات المحتوى بالذكاء الاصطناعي يمكنها رفع التفاعل بشكل ملحوظ.',
  },
  activation_drop: {
    label:         'User Activation Rate',
    label_ar:      'معدل تفعيل المستخدمين',
    metric:        'Activation %',
    unit:          '%',
    lowerBetter:   false,
    goalVerb:      'Reach activation of',
    goalVerb_ar:   'حقِّق معدل تفعيل بنسبة',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/advisory?type=roadmap',
    upsellCopy:    'AI-powered onboarding nudges can double activation rates.',
    upsellCopy_ar: 'تنبيهات التأهيل بالذكاء الاصطناعي يمكنها مضاعفة معدلات التفعيل.',
  },
  refund_spike: {
    label:         'Refund Rate',
    label_ar:      'معدل الاسترداد',
    metric:        'Refund %',
    unit:          '%',
    lowerBetter:   true,
    goalVerb:      'Keep refunds under',
    goalVerb_ar:   'أبقِ معدل الاسترداد تحت',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'High refunds signal a product quality or expectation problem — fix the root cause first.',
    upsellCopy_ar: 'الاسترداد المرتفع يشير إلى مشكلة جودة أو توقعات — أصلح السبب الجذري أولاً.',
  },
  aov_decline: {
    label:         'Average Order Value',
    label_ar:      'متوسط قيمة الطلب',
    metric:        'AOV (£)',
    unit:          '£',
    lowerBetter:   false,
    goalVerb:      'Reach AOV of',
    goalVerb_ar:   'حقِّق متوسط قيمة طلب بقيمة',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'AOV improvement needs a pricing and upsell strategy.',
    upsellCopy_ar: 'تحسين متوسط قيمة الطلب يحتاج إلى استراتيجية تسعير وبيع إضافي.',
  },
  traffic_source_shift: {
    label:         'Organic Traffic Share',
    label_ar:      'حصة الزيارات العضوية',
    metric:        'Organic %',
    unit:          '%',
    lowerBetter:   false,
    goalVerb:      'Maintain organic share of',
    goalVerb_ar:   'حافظ على حصة عضوية بنسبة',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/advisory?type=roadmap',
    upsellCopy:    'AI content and SEO automation can rebuild organic traffic.',
    upsellCopy_ar: 'محتوى الذكاء الاصطناعي وأتمتة SEO يمكنها إعادة بناء الزيارات العضوية.',
  },
  session_duration_drop: {
    label:         'Session Duration',
    label_ar:      'مدة الجلسة',
    metric:        'Avg session (seconds)',
    unit:          'sec',
    lowerBetter:   false,
    goalVerb:      'Reach avg session of',
    goalVerb_ar:   'حقِّق متوسط جلسة بمقدار',
    service:       'roadmap',
    serviceLabel:  'AI Implementation Roadmap',
    servicePrice:  '£99',
    serviceUrl:    '/advisory?type=roadmap',
    upsellCopy:    'AI personalisation can increase time-on-site significantly.',
    upsellCopy_ar: 'التخصيص بالذكاء الاصطناعي يمكنه زيادة وقت البقاء في الموقع بشكل ملحوظ.',
  },
  rating_decline: {
    label:         'Trustpilot Rating',
    label_ar:      'تقييم Trustpilot',
    metric:        'Rating (out of 5)',
    unit:          'stars',
    lowerBetter:   false,
    goalVerb:      'Reach rating of',
    goalVerb_ar:   'حقِّق تقييماً بقيمة',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'Rating recovery needs a brand and product response strategy.',
    upsellCopy_ar: 'استعادة التقييم تحتاج إلى استراتيجية علامة تجارية ومنتج.',
  },
  repeat_purchase_drop: {
    label:         'Repeat Purchase Rate',
    label_ar:      'معدل الشراء المتكرر',
    metric:        'Repeat customers %',
    unit:          '%',
    lowerBetter:   false,
    goalVerb:      'Maintain repeat purchase rate above',
    goalVerb_ar:   'حافظ على معدل شراء متكرر فوق',
    service:       'cpo',
    serviceLabel:  'Fractional CPO Session',
    servicePrice:  '£250',
    serviceUrl:    '/advisory?type=cpo',
    upsellCopy:    'Low repeat purchase rate signals a retention and loyalty problem.',
    upsellCopy_ar: 'انخفاض معدل الشراء المتكرر يشير إلى مشكلة في الاحتفاظ والولاء.',
  },
}

/** @deprecated Use goal.status from DB. Server is authority. Do not call client-side. */
export function getGoalStatus(
  currentValue: number | null,
  targetValue:  number,
  lowerBetter:  boolean,
  targetDate:   string
): 'active' | 'at_risk' | 'achieved' | 'missed' {
  if (currentValue === null) return 'active'
  const isAchieved = lowerBetter ? currentValue <= targetValue : currentValue >= targetValue
  if (isAchieved) return 'achieved'
  const isPastDeadline = new Date(targetDate) < new Date()
  if (isPastDeadline) return 'missed'
  return 'at_risk'
}

export function getGoalProgress(
  startValue:   number | null,
  currentValue: number | null,
  targetValue:  number,
  lowerBetter:  boolean
): number {
  if (startValue === null || currentValue === null) return 0
  if (startValue === targetValue) return 100
  const totalNeeded = Math.abs(targetValue - startValue)
  const achieved    = lowerBetter
    ? startValue - currentValue
    : currentValue - startValue
  return Math.min(100, Math.max(0, Math.round((achieved / totalNeeded) * 100)))
}
