export const privacy = {
  en: {
    title: 'Privacy Policy',
    updated: 'Last updated: May 2026',
    back: '← Back to signup',
    sections: [
      { title: '1. Who We Are', body: 'Elvanis is an AI-powered business diagnostic platform. We are committed to protecting your personal data and being transparent about how we use it. This Privacy Policy explains what data we collect, why we collect it, and how we use it.' },
      { title: '2. Data We Collect', body: 'We collect information you provide directly: your name, email address, business name, and account credentials. We collect business data from tools you connect to the Platform (Shopify, Jira, GA4, Intercom, Trustpilot) for the purpose of generating diagnostic signals. We collect usage data such as pages visited and features used to improve the Platform.' },
      { title: '3. How We Use Your Data', body: 'We use your data to provide and improve the Platform, generate diagnostic signals and recommendations, send service communications such as scan results and account notifications, and respond to support requests. We do not use your data for advertising purposes.' },
      { title: '4. Third-Party Tool Data', body: 'When you connect a third-party tool (Shopify, Jira, GA4, Intercom, Trustpilot), we request read-only access to specific data from that tool. We only request the minimum permissions necessary to generate diagnostic signals. We do not modify or write data to your connected tools.' },
      { title: '5. Data Storage and Security', body: 'Your data is stored securely on Supabase infrastructure hosted in the EU. We use industry-standard encryption for data in transit and at rest. Access tokens for connected tools are encrypted before storage. We do not store your third-party passwords.' },
      { title: '6. Data Sharing', body: 'We do not sell your personal data or business data to third parties. We share data with service providers who help us operate the Platform (Supabase for database, Groq for AI analysis, Vercel for hosting, Resend for email). These providers are bound by data processing agreements.' },
      { title: '7. AI Processing', body: 'Your business data is processed by AI models (OpenAI) to generate diagnostic signals. This processing is done on a per-request basis and your data is not used to train AI models. Diagnostic signals are stored in your account and are only visible to you.' },
      { title: '8. Data Retention', body: 'We retain your account data for as long as your account is active. If you deactivate your account, your data is retained for 30 days before permanent deletion. You may request immediate deletion by contacting us. Connected tool access tokens are deleted immediately upon disconnection.' },
      { title: '9. Your Rights (GDPR)', body: 'If you are located in the UK or EU, you have the right to access your personal data, correct inaccurate data, request deletion of your data, restrict processing of your data, and data portability. To exercise these rights, contact us through the support section of your profile.' },
      { title: '10. Cookies', body: 'We use essential cookies for authentication and session management. We use analytics cookies to understand how the Platform is used. You can control cookie preferences through your browser settings. Disabling essential cookies will prevent you from logging in.' },
      { title: '11. International Transfers', body: 'Your data may be processed in countries outside the UK and EU by our service providers. We ensure appropriate safeguards are in place for such transfers in compliance with applicable data protection laws.' },
      { title: "12. Children's Privacy", body: 'The Platform is not intended for use by individuals under the age of 18. We do not knowingly collect personal data from children. If you believe we have collected data from a child, please contact us immediately.' },
      { title: '13. Changes to This Policy', body: 'We may update this Privacy Policy from time to time. We will notify you of significant changes by email. The date at the top of this page indicates when the policy was last updated.' },
      { title: '14. Contact Us', body: 'If you have questions about this Privacy Policy or how we handle your data, please contact us through the support section of your profile or via the chat widget on the Platform.' },
    ],
    footer: '© 2026 Elvanis. All rights reserved.',
    terms_link: 'Terms of Service',
  },
  ar: {
    title: 'سياسة الخصوصية',
    updated: 'آخر تحديث: مايو 2026',
    back: 'العودة إلى التسجيل →',
    sections: [
      { title: '1. من نحن', body: 'إلفانيس منصة تشخيص أعمال مدعومة بالذكاء الاصطناعي. نحن ملتزمون بحماية بياناتك الشخصية والشفافية في كيفية استخدامها. توضح سياسة الخصوصية هذه البيانات التي نجمعها ولماذا نجمعها وكيف نستخدمها.' },
      { title: '2. البيانات التي نجمعها', body: 'نجمع المعلومات التي تقدمها مباشرةً: اسمك وعنوان بريدك الإلكتروني واسم شركتك وبيانات اعتماد حسابك. نجمع بيانات الأعمال من الأدوات التي تربطها بالمنصة لغرض توليد الإشارات التشخيصية. نجمع بيانات الاستخدام لتحسين المنصة.' },
      { title: '3. كيف نستخدم بياناتك', body: 'نستخدم بياناتك لتقديم المنصة وتحسينها، وتوليد الإشارات التشخيصية والتوصيات، وإرسال اتصالات الخدمة، والرد على طلبات الدعم. لا نستخدم بياناتك لأغراض إعلانية.' },
      { title: '4. بيانات أدوات الطرف الثالث', body: 'عند ربط أداة طرف ثالث، نطلب وصولاً للقراءة فقط إلى بيانات محددة من تلك الأداة. نطلب فقط الحد الأدنى من الأذونات اللازمة لتوليد الإشارات التشخيصية. لا نعدّل أو نكتب بيانات إلى أدواتك المتصلة.' },
      { title: '5. تخزين البيانات والأمان', body: 'تُخزَّن بياناتك بأمان على بنية Supabase التحتية المستضافة في الاتحاد الأوروبي. نستخدم تشفيراً وفق معايير الصناعة للبيانات أثناء النقل وعند الراحة. تُشفَّر رموز الوصول للأدوات المتصلة قبل التخزين.' },
      { title: '6. مشاركة البيانات', body: 'لا نبيع بياناتك الشخصية أو بيانات أعمالك لأطراف ثالثة. نشارك البيانات مع مزودي الخدمة الذين يساعدوننا في تشغيل المنصة. هؤلاء المزودون مقيدون باتفاقيات معالجة البيانات.' },
      { title: '7. المعالجة بالذكاء الاصطناعي', body: 'تُعالَج بيانات أعمالك بواسطة نماذج ذكاء اصطناعي لتوليد الإشارات التشخيصية. تتم هذه المعالجة على أساس كل طلب على حدة ولا تُستخدم بياناتك لتدريب نماذج الذكاء الاصطناعي.' },
      { title: '8. الاحتفاظ بالبيانات', body: 'نحتفظ ببيانات حسابك طالما كان حسابك نشطاً. إذا قمت بإلغاء تنشيط حسابك، تُحتفظ ببياناتك لمدة 30 يوماً قبل الحذف الدائم. يمكنك طلب الحذف الفوري بالتواصل معنا.' },
      { title: '9. حقوقك (اللائحة العامة لحماية البيانات)', body: 'إذا كنت في المملكة المتحدة أو الاتحاد الأوروبي، فلديك حق الوصول إلى بياناتك الشخصية وتصحيحها وطلب حذفها وتقييد معالجتها ونقلها. لممارسة هذه الحقوق، تواصل معنا عبر قسم الدعم في ملفك الشخصي.' },
      { title: '10. ملفات تعريف الارتباط', body: 'نستخدم ملفات تعريف الارتباط الأساسية للمصادقة وإدارة الجلسة. نستخدم ملفات تعريف الارتباط التحليلية لفهم كيفية استخدام المنصة. يمكنك التحكم في تفضيلات ملفات تعريف الارتباط من خلال إعدادات متصفحك.' },
      { title: '11. النقل الدولي', body: 'قد تُعالَج بياناتك في دول خارج المملكة المتحدة والاتحاد الأوروبي من قبل مزودي خدماتنا. نضمن وجود ضمانات مناسبة لمثل هذه التحويلات وفقاً لقوانين حماية البيانات المعمول بها.' },
      { title: '12. خصوصية الأطفال', body: 'المنصة غير مخصصة للاستخدام من قبل الأفراد دون سن 18 عاماً. لا نجمع عمداً بيانات شخصية من الأطفال. إذا كنت تعتقد أننا جمعنا بيانات من طفل، يرجى التواصل معنا فوراً.' },
      { title: '13. التغييرات على هذه السياسة', body: 'قد نحدّث سياسة الخصوصية هذه من وقت لآخر. سنخطرك بالتغييرات المهمة عبر البريد الإلكتروني. يشير التاريخ في أعلى هذه الصفحة إلى آخر تحديث للسياسة.' },
      { title: '14. تواصل معنا', body: 'إذا كانت لديك أسئلة حول سياسة الخصوصية هذه أو كيفية تعاملنا مع بياناتك، يرجى التواصل معنا عبر قسم الدعم في ملفك الشخصي أو عبر أداة المحادثة على المنصة.' },
    ],
    footer: '© 2026 إلفانيس. جميع الحقوق محفوظة.',
    terms_link: 'شروط الخدمة',
  },
}
