export const terms = {
  en: {
    title: 'Terms of Service',
    updated: 'Last updated: May 2026',
    back: '← Back to signup',
    sections: [
      { title: '1. Acceptance of Terms', body: 'By accessing or using Elvanis ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform. These terms apply to all users including founders on free and paid plans.' },
      { title: '2. Description of Service', body: 'Elvanis is an AI-powered business diagnostic platform that connects to your operational tools, analyses your data, and generates diagnostic signals and recommendations. The Platform is provided on a subscription basis with a free tier and a paid Navigator tier.' },
      { title: '3. User Accounts', body: 'You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate and complete information when creating your account. You must notify us immediately of any unauthorised use of your account.' },
      { title: '4. Data and Privacy', body: 'By connecting your tools to Elvanis, you grant us permission to read data from those tools for the purpose of generating diagnostic signals and recommendations. We do not sell your data to third parties. Please refer to our Privacy Policy for full details on how we handle your data.' },
      { title: '5. Acceptable Use', body: 'You agree not to use the Platform for any unlawful purpose, to attempt to gain unauthorised access to any part of the Platform, to interfere with the operation of the Platform, or to use the Platform to transmit harmful or malicious content.' },
      { title: '6. Subscription and Billing', body: 'The free tier is available indefinitely at no cost. The Navigator plan is billed monthly at £29. Subscriptions are renewed manually — you will be notified before your plan expires. We reserve the right to change pricing with 30 days notice.' },
      { title: '7. Intellectual Property', body: 'All content, features, and functionality of the Platform are owned by Elvanis and are protected by applicable intellectual property laws. You retain ownership of your data. We retain ownership of the diagnostic models, algorithms, and platform technology.' },
      { title: '8. Disclaimer of Warranties', body: 'The Platform is provided "as is" without warranties of any kind. We do not guarantee that the Platform will be error-free, uninterrupted, or that the diagnostic signals generated will be accurate or complete. Business decisions made based on Platform output are your sole responsibility.' },
      { title: '9. Limitation of Liability', body: 'To the maximum extent permitted by law, Elvanis shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.' },
      { title: '10. Termination', body: 'We reserve the right to suspend or terminate your account if you violate these terms. You may cancel your account at any time from your profile settings. Upon termination, your data will be retained for 30 days before permanent deletion.' },
      { title: '11. Changes to Terms', body: 'We may update these terms from time to time. We will notify you of significant changes by email. Continued use of the Platform after changes constitutes acceptance of the updated terms.' },
      { title: '12. Governing Law', body: 'These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.' },
      { title: '13. Contact', body: 'If you have questions about these terms, please contact us through the support section of your profile or via the chat widget on the Platform.' },
    ],
    footer: '© 2026 Elvanis. All rights reserved.',
    privacy_link: 'Privacy Policy',
  },
  ar: {
    title: 'شروط الخدمة',
    updated: 'آخر تحديث: مايو 2026',
    back: 'العودة إلى التسجيل →',
    sections: [
      { title: '1. قبول الشروط', body: 'بالوصول إلى إلفانيس ("المنصة") أو استخدامها، فإنك توافق على الالتزام بشروط الخدمة هذه. إذا كنت لا توافق على هذه الشروط، يرجى عدم استخدام المنصة. تنطبق هذه الشروط على جميع المستخدمين بما في ذلك المؤسسون في الخطط المجانية والمدفوعة.' },
      { title: '2. وصف الخدمة', body: 'إلفانيس منصة تشخيص أعمال مدعومة بالذكاء الاصطناعي تتصل بأدواتك التشغيلية وتحلل بياناتك وتولد إشارات تشخيصية وتوصيات. تُقدَّم المنصة على أساس الاشتراك مع مستوى مجاني ومستوى Navigator مدفوع.' },
      { title: '3. حسابات المستخدمين', body: 'أنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك. توافق على تقديم معلومات دقيقة وكاملة عند إنشاء حسابك. يجب إخطارنا فوراً بأي استخدام غير مصرح به لحسابك.' },
      { title: '4. البيانات والخصوصية', body: 'بربط أدواتك بإلفانيس، فإنك تمنحنا إذناً بقراءة البيانات من تلك الأدوات لغرض توليد الإشارات التشخيصية والتوصيات. لا نبيع بياناتك لأطراف ثالثة. يرجى الرجوع إلى سياسة الخصوصية للتفاصيل الكاملة.' },
      { title: '5. الاستخدام المقبول', body: 'توافق على عدم استخدام المنصة لأي غرض غير قانوني، أو محاولة الوصول غير المصرح به إلى أي جزء من المنصة، أو التدخل في تشغيل المنصة، أو استخدام المنصة لنقل محتوى ضار أو خبيث.' },
      { title: '6. الاشتراك والفوترة', body: 'المستوى المجاني متاح إلى أجل غير مسمى بدون تكلفة. خطة Navigator تُفوتر شهرياً بمبلغ 29 جنيهاً إسترلينياً. تُجدَّد الاشتراكات يدوياً — ستُخطر قبل انتهاء صلاحية خطتك. نحتفظ بحق تغيير الأسعار مع إشعار مدته 30 يوماً.' },
      { title: '7. الملكية الفكرية', body: 'جميع محتويات وميزات ووظائف المنصة مملوكة لإلفانيس ومحمية بموجب قوانين الملكية الفكرية المعمول بها. تحتفظ بملكية بياناتك. نحتفظ بملكية النماذج التشخيصية والخوارزميات وتقنية المنصة.' },
      { title: '8. إخلاء مسؤولية الضمانات', body: 'تُقدَّم المنصة "كما هي" دون ضمانات من أي نوع. لا نضمن أن المنصة ستكون خالية من الأخطاء أو غير منقطعة، أو أن الإشارات التشخيصية المولَّدة ستكون دقيقة أو كاملة. قرارات الأعمال المتخذة بناءً على مخرجات المنصة هي مسؤوليتك وحدك.' },
      { title: '9. تحديد المسؤولية', body: 'إلى أقصى حد يسمح به القانون، لن تكون إلفانيس مسؤولة عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية ناشئة عن استخدامك للمنصة. لن تتجاوز مسؤوليتنا الإجمالية المبلغ الذي دفعته لنا في الـ 12 شهراً السابقة للمطالبة.' },
      { title: '10. الإنهاء', body: 'نحتفظ بحق تعليق حسابك أو إنهائه إذا انتهكت هذه الشروط. يمكنك إلغاء حسابك في أي وقت من إعدادات ملفك الشخصي. عند الإنهاء، ستُحتفظ ببياناتك لمدة 30 يوماً قبل الحذف الدائم.' },
      { title: '11. التغييرات على الشروط', body: 'قد نحدّث هذه الشروط من وقت لآخر. سنخطرك بالتغييرات المهمة عبر البريد الإلكتروني. استمرار استخدام المنصة بعد التغييرات يُشكّل قبولاً للشروط المحدَّثة.' },
      { title: '12. القانون الحاكم', body: 'تخضع هذه الشروط لقوانين إنجلترا وويلز. تخضع أي نزاعات للاختصاص القضائي الحصري لمحاكم إنجلترا وويلز.' },
      { title: '13. التواصل', body: 'إذا كانت لديك أسئلة حول هذه الشروط، يرجى التواصل معنا عبر قسم الدعم في ملفك الشخصي أو عبر أداة المحادثة على المنصة.' },
    ],
    footer: '© 2026 إلفانيس. جميع الحقوق محفوظة.',
    privacy_link: 'سياسة الخصوصية',
  },
}
